### ISSUE TITLE
Migration from Metro Mini

### ISSUE THREAD

**Issue by t0mpr1c3** [AllYarnsAreBeautiful/ayab-hardware#15]
Eventually I would like to move to a v3 interface that does not rely on the Metro Mini. At some point in the future Adafruit will retire it, and there is no replacement board with the same form factor.

The closest like-for-like replacement would be the Arduino Nano Every.
- Open source.
- Functionally equivalent.
- Nano form factor is almost the same size.
- Similar price.

The Every even offers a couple of small improvements.
- More flash, more RAM.
- Castellated and no components on the back, so it can be soldered directly to the PCB.

Nevertheless, I am also looking at the possibility of putting a microcontroller directly on the interface.
- Must have: Arduino-compatible IDE, run at 5V.
- Strong preference: fast Arm M0 or M0+ with at least as much flash and RAM as the Every.
- Nice to have: enough IO pins that expanders are no longer necessary, hardware support for USB 2.x.

AFAIK the only chip that meets all these criteria is the NUC123LD4AN0 as used on the DFRduino M0 (SKU: DFR0392). I'm playing around with a DFRduino M0 at the moment to get an idea of how much work it would take to retool the firmware.

**Comment by t0mpr1c3** [comment]
Files for Nano prototype are here: https://github.com/t0mpr1c3/ayab-hardware/tree/nano/Shieldv2x

although I should probably move them to a new folder Shieldv3x. I'll have some PCBs made in the next couple of weeks.

**Comment by cb88** [comment]
> Files for Nano prototype are here: https://github.com/t0mpr1c3/ayab-hardware/tree/nano/Shieldv2x
> 
> although I should probably move them to a new folder Shieldv3x. I'll have some PCBs made in the next couple of weeks.

What's the status of the Nano Every prototype? I picked up a KH-910 and am planning on getting it going for Christmas for my mother and sisters ;-) ... I'm contemplating which interface board to order (probably from JLCPCB) since I like it better than the shield.

One alternative you might consider is the PSOC5  and you probably wouldn't need IO expansion then. https://www.sparkfun.com/products/13714

RISCV could be possible also the Longan Nano is 3.3v but most of the pins are 5V tolerant... even if they can't directly drive 5V. that board also has rust support if you wanted to tickle that itch.

I have a fondness for PIC32/Chipkit but it clearly doesn't meet your IO requirements at all... 

USB port type really doesn't matter that much IMO and USB 2.0 is gonna be supported virtually forever, its not a big deal to interface to original low speed devices even now from a USB 3.1 gen 2 port etc... on most devices worst case you can always go through a hub anyway.

**Comment by t0mpr1c3** [comment]
I've built a prototype but I haven't made any attempt to migrate the code
base.

**Comment by VIPQualityPost** [comment]
hi,
I recently started working on developing my own replacement mainboard for these machines, only to recently find your project. My board is designed for low-cost assembly and based on the STM32F103, using USB C for connection to PC and an on-board power supply.  AYAB seems really interesting and I am more of a hardware guy than software and it seems you have done a lot of legwork here on that front- I am happy to lend a hand with any hardware design, schematic review, etc. I would love to help out. Also, the link to join your discord does not work.

**Comment by t0mpr1c3** [comment]
Try this link: https://discord.gg/Gpwakzys

I think that currently, the consensus long term goal is to migrate the desktop software to a webapp and the hardware to ESP32.

The short term consensus is to stick with Adafruit mini metro, although personally if I ever get around to manufacturing the boards again I will be looking to switch to the Arduino Every which is more or less a drop in replacement.

**Comment by VIPQualityPost** [comment]
Closing as new hardware is, indeed, ESP32 based.
